project:
  type: website
  output-dir: docs
  
website:
  title: "R 101"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - R101.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/2olomon/GitRDone
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Solomon Garland"

format:
  html:
    theme: vapor
    toc: true

editor: source

